import {readFileSync,mkdirSync,writeFileSync,cpSync,chmodSync} from 'node:fs';
import {resolve} from 'node:path';
import {homedir} from 'node:os';
import {createHash} from 'node:crypto';
import {root} from '../src/config.mjs';
if(process.platform!=='darwin')throw new Error('This installer currently supports macOS only');
const dir=resolve(homedir(),'.local/share/narciso/browser-runtime');
mkdirSync(dir,{recursive:true,mode:0o700});
writeFileSync(resolve(dir,'package.json'),'{"private":true,"type":"module"}\n');
cpSync(resolve(root,'browser'),resolve(dir,'browser'),{recursive:true});
mkdirSync(resolve(dir,'src'),{recursive:true});
cpSync(resolve(root,'src/config.mjs'),resolve(dir,'src/config.mjs'));
const manifest=JSON.parse(readFileSync(resolve(dir,'browser/extension/manifest.json')));
const id=createHash('sha256').update(Buffer.from(manifest.key,'base64')).digest('hex').slice(0,32).replace(/[0-9a-f]/g,c=>String.fromCharCode(97+parseInt(c,16)));
const quote=s=>"'"+s.replaceAll("'","'\\''")+"'";
const launcher=resolve(dir,'launch-host');
writeFileSync(launcher,'#!/bin/sh\nexec '+quote(process.execPath)+' '+quote(resolve(dir,'browser/native-host.mjs'))+' "$@"\n',{mode:0o700});
chmodSync(launcher,0o700);
const hosts=resolve(homedir(),'Library/Application Support/Google/Chrome/NativeMessagingHosts');
mkdirSync(hosts,{recursive:true});
writeFileSync(resolve(hosts,'ai.narciso.browser.json'),JSON.stringify({name:'ai.narciso.browser',description:'Narciso local browser bridge',path:launcher,type:'stdio',allowed_origins:[`chrome-extension://${id}/`]},null,2),{mode:0o600});
console.log(JSON.stringify({extensionId:id,loadUnpacked:resolve(dir,'browser/extension'),next:'Load this extension in the Chrome profile you want Narciso to use. Chrome must remain open.'},null,2));
